### ISSUE TITLE
Docker image Iceberg Rest Catalog in arm64  

### ISSUE THREAD

**Issue by caravori** [SIDN/entrada2#1]
# Description

[docker-compose.yml]
```
iceberg-rest-catalog:
    image: sidnlabs/iceberg-restcatalog-server:0.0.1
    profiles: ["dev","test"]
    restart: always
```
Using docker inspect the Architecture from image is arm64, causing errors if you are using x86_64 processors. 
[docker inspect  sidnlabs/iceberg-restcatalog-server:0.0.1]
```
"Architecture": "arm64",
"Variant": "v8",
"Os": "linux",
```
This causes the iceberg-restcatalog-server to not run java correctly.  Resulting into this error:
[docker output]
```
exec /usr/lib/jvm/java-21-openjdk/bin/java: exec format error
```
 # Hotfix 
Build your own iceberg-restcatalog-server image using docker build.
```
git clone https://github.com/SIDN/iceberg-rest-catalog-server && cd iceberg-rest-catalog-server/ && export TOOL_VERSION=0.1.1 &&
mvn package && docker build --tag=iceberg-rest-catalog-server:$TOOL_VERSION .
