### ISSUE TITLE
mc config call deprecated

### ISSUE THREAD

**Issue by ukkarikari** [SIDN/entrada2#19]
mc has deprecated the ```mc config command```, as per https://github.com/minio/minio/issues/21327 , which breaks the current docker script.

as a temporary solution, one may change the docker-compose.yml file to pull an older image of minio/mc such as in the snippet below
```
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    env_file:
       - path: ./docker.env
    volumes:
      - entradaMinioVolume:/data:rw
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    links:
      - rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
  createbucket:
    image: minio/mc:RELEASE.2025-04-08T15-39-49Z
    env_file:
       - path: ./docker.env
    depends_on:
      minio:
        condition: service_healthy
    links:
      - minio
    entrypoint: ["/bin/sh","/init-minio.sh"]
    volumes:
       - ./init-minio.sh:/init-minio.sh
```
